on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write
  contents: read
  id-token: write
  issues: write
  packages: write
  pull-requests: write
  security-events: write

jobs:
  ci:
    name: ci
    uses: ./.github/workflows/CI.yml

  automation_workflow:
    name: automation_workflow
    needs: ci
    if: ${{ success() }}
    uses: preetham-coupa/RestSharpWithNUnit/.github/workflows/workflow_automation.yml@main
    with:
      url_of_instance: "https://api.publicapis.org/entries"
      pr_id: "01234" 